service: you-sloth
useDotenv: true # If set to 'true', environment variables will be automatically loaded from .env files

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  stage: dev
  region: eu-west-3

functions:
  sendSms:
    handler: handler.sendSms
    role: !GetAtt assumePolicyRole.Arn
    environment:
      REGION: ${env:REGION}
      SMS_MESSAGE: ${env:SMS_MESSAGE}
      PHONE_NUMBER: ${env:PHONE_NUMBER}

resources:
  Resources:
    assumePolicyRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ASSUME_POLICY
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole

        Policies:
          - PolicyName: 'sendSmsPolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: '*'
